/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import { customInstant } from './base/BaseApi';
import type {
  ChapterDto,
  CourseDetailDto,
  CourseDto,
  EnrollmentDto,
  FileUploadResponse,
  QuestionsResponseDto,
  SectionDto,
  UploadFileBody,
  UserAnswerDto,
  UserChapterDto,
  UserInfoDto,
} from './model';
import { useMutation, useQuery } from '@tanstack/vue-query';
import type {
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType,
} from '@tanstack/vue-query';
import { computed, unref } from 'vue';
import type { MaybeRef } from 'vue';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 根據單元ID取得單元詳細資訊
 * @summary 依ID取得單元
 */
export const getSectionById = (
  id: MaybeRef<number>,
  options?: SecondParameter<typeof customInstant>,
  signal?: AbortSignal
) => {
  id = unref(id);

  return customInstant<SectionDto>(
    { url: `/api/v1/sections/${encodeURIComponent(String(id))}`, method: 'GET', signal },
    options
  );
};

export const getGetSectionByIdQueryKey = (id?: MaybeRef<number>) => {
  return ['api', 'v1', 'sections', id] as const;
};

export const getGetSectionByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getSectionById>>,
  TError = unknown,
>(
  id: MaybeRef<number>,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSectionById>>, TError, TData>>;
    request?: SecondParameter<typeof customInstant>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetSectionByIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getSectionById>>> = ({ signal }) =>
    getSectionById(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!unref(id)),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getSectionById>>, TError, TData>;
};

export type GetSectionByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getSectionById>>>;
export type GetSectionByIdQueryError = unknown;

/**
 * @summary 依ID取得單元
 */

export function useGetSectionById<
  TData = Awaited<ReturnType<typeof getSectionById>>,
  TError = unknown,
>(
  id: MaybeRef<number>,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSectionById>>, TError, TData>>;
    request?: SecondParameter<typeof customInstant>;
  },
  queryClient?: QueryClient
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetSectionByIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}

/**
 * 根據單元ID更新單元資訊
 * @summary 更新單元
 */
export const updateSection = (
  id: MaybeRef<number>,
  sectionDto: MaybeRef<SectionDto>,
  options?: SecondParameter<typeof customInstant>
) => {
  id = unref(id);
  sectionDto = unref(sectionDto);

  return customInstant<SectionDto>(
    {
      url: `/api/v1/sections/${encodeURIComponent(String(id))}`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: sectionDto,
    },
    options
  );
};

export const getUpdateSectionMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateSection>>,
    TError,
    { id: number; data: SectionDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstant>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateSection>>,
  TError,
  { id: number; data: SectionDto },
  TContext
> => {
  const mutationKey = ['updateSection'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateSection>>,
    { id: number; data: SectionDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateSection(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateSectionMutationResult = NonNullable<Awaited<ReturnType<typeof updateSection>>>;
export type UpdateSectionMutationBody = SectionDto;
export type UpdateSectionMutationError = unknown;

/**
 * @summary 更新單元
 */
export const useUpdateSection = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateSection>>,
      TError,
      { id: number; data: SectionDto },
      TContext
    >;
    request?: SecondParameter<typeof customInstant>;
  },
  queryClient?: QueryClient
): UseMutationReturnType<
  Awaited<ReturnType<typeof updateSection>>,
  TError,
  { id: number; data: SectionDto },
  TContext
> => {
  const mutationOptions = getUpdateSectionMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * 根據單元ID刪除單元
 * @summary 刪除單元
 */
export const deleteSection = (
  id: MaybeRef<number>,
  options?: SecondParameter<typeof customInstant>
) => {
  id = unref(id);

  return customInstant<void>(
    { url: `/api/v1/sections/${encodeURIComponent(String(id))}`, method: 'DELETE' },
    options
  );
};

export const getDeleteSectionMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteSection>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customInstant>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteSection>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ['deleteSection'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteSection>>, { id: number }> = (
    props
  ) => {
    const { id } = props ?? {};

    return deleteSection(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteSectionMutationResult = NonNullable<Awaited<ReturnType<typeof deleteSection>>>;

export type DeleteSectionMutationError = unknown;

/**
 * @summary 刪除單元
 */
export const useDeleteSection = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteSection>>,
      TError,
      { id: number },
      TContext
    >;
    request?: SecondParameter<typeof customInstant>;
  },
  queryClient?: QueryClient
): UseMutationReturnType<
  Awaited<ReturnType<typeof deleteSection>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions = getDeleteSectionMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * 根據課程ID取得課程詳細資訊
 * @summary 依ID取得課程
 */
export const getCourseById = (
  id: MaybeRef<number>,
  options?: SecondParameter<typeof customInstant>,
  signal?: AbortSignal
) => {
  id = unref(id);

  return customInstant<CourseDto>(
    { url: `/api/v1/courses/${encodeURIComponent(String(id))}`, method: 'GET', signal },
    options
  );
};

export const getGetCourseByIdQueryKey = (id?: MaybeRef<number>) => {
  return ['api', 'v1', 'courses', id] as const;
};

export const getGetCourseByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getCourseById>>,
  TError = unknown,
>(
  id: MaybeRef<number>,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCourseById>>, TError, TData>>;
    request?: SecondParameter<typeof customInstant>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetCourseByIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCourseById>>> = ({ signal }) =>
    getCourseById(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!unref(id)),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getCourseById>>, TError, TData>;
};

export type GetCourseByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getCourseById>>>;
export type GetCourseByIdQueryError = unknown;

/**
 * @summary 依ID取得課程
 */

export function useGetCourseById<
  TData = Awaited<ReturnType<typeof getCourseById>>,
  TError = unknown,
>(
  id: MaybeRef<number>,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCourseById>>, TError, TData>>;
    request?: SecondParameter<typeof customInstant>;
  },
  queryClient?: QueryClient
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetCourseByIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}

/**
 * 根據課程ID更新課程資訊
 * @summary 更新課程
 */
export const updateCourse = (
  id: MaybeRef<number>,
  courseDto: MaybeRef<CourseDto>,
  options?: SecondParameter<typeof customInstant>
) => {
  id = unref(id);
  courseDto = unref(courseDto);

  return customInstant<CourseDto>(
    {
      url: `/api/v1/courses/${encodeURIComponent(String(id))}`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: courseDto,
    },
    options
  );
};

export const getUpdateCourseMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateCourse>>,
    TError,
    { id: number; data: CourseDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstant>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateCourse>>,
  TError,
  { id: number; data: CourseDto },
  TContext
> => {
  const mutationKey = ['updateCourse'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateCourse>>,
    { id: number; data: CourseDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateCourse(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateCourseMutationResult = NonNullable<Awaited<ReturnType<typeof updateCourse>>>;
export type UpdateCourseMutationBody = CourseDto;
export type UpdateCourseMutationError = unknown;

/**
 * @summary 更新課程
 */
export const useUpdateCourse = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateCourse>>,
      TError,
      { id: number; data: CourseDto },
      TContext
    >;
    request?: SecondParameter<typeof customInstant>;
  },
  queryClient?: QueryClient
): UseMutationReturnType<
  Awaited<ReturnType<typeof updateCourse>>,
  TError,
  { id: number; data: CourseDto },
  TContext
> => {
  const mutationOptions = getUpdateCourseMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * 根據課程ID刪除課程
 * @summary 刪除課程
 */
export const deleteCourse = (
  id: MaybeRef<number>,
  options?: SecondParameter<typeof customInstant>
) => {
  id = unref(id);

  return customInstant<void>(
    { url: `/api/v1/courses/${encodeURIComponent(String(id))}`, method: 'DELETE' },
    options
  );
};

export const getDeleteCourseMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteCourse>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customInstant>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteCourse>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ['deleteCourse'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteCourse>>, { id: number }> = (
    props
  ) => {
    const { id } = props ?? {};

    return deleteCourse(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteCourseMutationResult = NonNullable<Awaited<ReturnType<typeof deleteCourse>>>;

export type DeleteCourseMutationError = unknown;

/**
 * @summary 刪除課程
 */
export const useDeleteCourse = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteCourse>>,
      TError,
      { id: number },
      TContext
    >;
    request?: SecondParameter<typeof customInstant>;
  },
  queryClient?: QueryClient
): UseMutationReturnType<
  Awaited<ReturnType<typeof deleteCourse>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions = getDeleteCourseMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * 根據章節ID取得章節詳細資訊
 * @summary 依ID取得章節
 */
export const getChapterById = (
  id: MaybeRef<number>,
  options?: SecondParameter<typeof customInstant>,
  signal?: AbortSignal
) => {
  id = unref(id);

  return customInstant<ChapterDto>(
    { url: `/api/v1/chapters/${encodeURIComponent(String(id))}`, method: 'GET', signal },
    options
  );
};

export const getGetChapterByIdQueryKey = (id?: MaybeRef<number>) => {
  return ['api', 'v1', 'chapters', id] as const;
};

export const getGetChapterByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getChapterById>>,
  TError = unknown,
>(
  id: MaybeRef<number>,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getChapterById>>, TError, TData>>;
    request?: SecondParameter<typeof customInstant>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetChapterByIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getChapterById>>> = ({ signal }) =>
    getChapterById(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!unref(id)),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getChapterById>>, TError, TData>;
};

export type GetChapterByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getChapterById>>>;
export type GetChapterByIdQueryError = unknown;

/**
 * @summary 依ID取得章節
 */

export function useGetChapterById<
  TData = Awaited<ReturnType<typeof getChapterById>>,
  TError = unknown,
>(
  id: MaybeRef<number>,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getChapterById>>, TError, TData>>;
    request?: SecondParameter<typeof customInstant>;
  },
  queryClient?: QueryClient
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetChapterByIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}

/**
 * 根據章節ID更新章節資訊
 * @summary 更新章節
 */
export const updateChapter = (
  id: MaybeRef<number>,
  chapterDto: MaybeRef<ChapterDto>,
  options?: SecondParameter<typeof customInstant>
) => {
  id = unref(id);
  chapterDto = unref(chapterDto);

  return customInstant<ChapterDto>(
    {
      url: `/api/v1/chapters/${encodeURIComponent(String(id))}`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: chapterDto,
    },
    options
  );
};

export const getUpdateChapterMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateChapter>>,
    TError,
    { id: number; data: ChapterDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstant>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateChapter>>,
  TError,
  { id: number; data: ChapterDto },
  TContext
> => {
  const mutationKey = ['updateChapter'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateChapter>>,
    { id: number; data: ChapterDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateChapter(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateChapterMutationResult = NonNullable<Awaited<ReturnType<typeof updateChapter>>>;
export type UpdateChapterMutationBody = ChapterDto;
export type UpdateChapterMutationError = unknown;

/**
 * @summary 更新章節
 */
export const useUpdateChapter = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateChapter>>,
      TError,
      { id: number; data: ChapterDto },
      TContext
    >;
    request?: SecondParameter<typeof customInstant>;
  },
  queryClient?: QueryClient
): UseMutationReturnType<
  Awaited<ReturnType<typeof updateChapter>>,
  TError,
  { id: number; data: ChapterDto },
  TContext
> => {
  const mutationOptions = getUpdateChapterMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * 根據章節ID刪除章節
 * @summary 刪除章節
 */
export const deleteChapter = (
  id: MaybeRef<number>,
  options?: SecondParameter<typeof customInstant>
) => {
  id = unref(id);

  return customInstant<void>(
    { url: `/api/v1/chapters/${encodeURIComponent(String(id))}`, method: 'DELETE' },
    options
  );
};

export const getDeleteChapterMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteChapter>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customInstant>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteChapter>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ['deleteChapter'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteChapter>>, { id: number }> = (
    props
  ) => {
    const { id } = props ?? {};

    return deleteChapter(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteChapterMutationResult = NonNullable<Awaited<ReturnType<typeof deleteChapter>>>;

export type DeleteChapterMutationError = unknown;

/**
 * @summary 刪除章節
 */
export const useDeleteChapter = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteChapter>>,
      TError,
      { id: number },
      TContext
    >;
    request?: SecondParameter<typeof customInstant>;
  },
  queryClient?: QueryClient
): UseMutationReturnType<
  Awaited<ReturnType<typeof deleteChapter>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions = getDeleteChapterMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * 建立新的課程單元
 * @summary 新增單元
 */
export const createSection = (
  sectionDto: MaybeRef<SectionDto>,
  options?: SecondParameter<typeof customInstant>,
  signal?: AbortSignal
) => {
  sectionDto = unref(sectionDto);

  return customInstant<SectionDto>(
    {
      url: `/api/v1/sections`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: sectionDto,
      signal,
    },
    options
  );
};

export const getCreateSectionMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createSection>>,
    TError,
    { data: SectionDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstant>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createSection>>,
  TError,
  { data: SectionDto },
  TContext
> => {
  const mutationKey = ['createSection'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createSection>>,
    { data: SectionDto }
  > = (props) => {
    const { data } = props ?? {};

    return createSection(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateSectionMutationResult = NonNullable<Awaited<ReturnType<typeof createSection>>>;
export type CreateSectionMutationBody = SectionDto;
export type CreateSectionMutationError = unknown;

/**
 * @summary 新增單元
 */
export const useCreateSection = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createSection>>,
      TError,
      { data: SectionDto },
      TContext
    >;
    request?: SecondParameter<typeof customInstant>;
  },
  queryClient?: QueryClient
): UseMutationReturnType<
  Awaited<ReturnType<typeof createSection>>,
  TError,
  { data: SectionDto },
  TContext
> => {
  const mutationOptions = getCreateSectionMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * 生成問題
 * @summary 生成問題
 */
export const generateQuestion = (
  generateQuestionBody: MaybeRef<string>,
  options?: SecondParameter<typeof customInstant>,
  signal?: AbortSignal
) => {
  generateQuestionBody = unref(generateQuestionBody);

  return customInstant<QuestionsResponseDto>(
    {
      url: `/api/v1/generate/question`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: generateQuestionBody,
      signal,
    },
    options
  );
};

export const getGenerateQuestionMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof generateQuestion>>,
    TError,
    { data: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstant>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof generateQuestion>>,
  TError,
  { data: string },
  TContext
> => {
  const mutationKey = ['generateQuestion'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof generateQuestion>>,
    { data: string }
  > = (props) => {
    const { data } = props ?? {};

    return generateQuestion(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type GenerateQuestionMutationResult = NonNullable<
  Awaited<ReturnType<typeof generateQuestion>>
>;
export type GenerateQuestionMutationBody = string;
export type GenerateQuestionMutationError = unknown;

/**
 * @summary 生成問題
 */
export const useGenerateQuestion = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof generateQuestion>>,
      TError,
      { data: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstant>;
  },
  queryClient?: QueryClient
): UseMutationReturnType<
  Awaited<ReturnType<typeof generateQuestion>>,
  TError,
  { data: string },
  TContext
> => {
  const mutationOptions = getGenerateQuestionMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * 生成課程
 * @summary 生成課程
 */
export const generateCourse = (
  userAnswerDto: MaybeRef<UserAnswerDto[]>,
  options?: SecondParameter<typeof customInstant>,
  signal?: AbortSignal
) => {
  userAnswerDto = unref(userAnswerDto);

  return customInstant<void>(
    {
      url: `/api/v1/generate/course`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: userAnswerDto,
      signal,
    },
    options
  );
};

export const getGenerateCourseMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof generateCourse>>,
    TError,
    { data: UserAnswerDto[] },
    TContext
  >;
  request?: SecondParameter<typeof customInstant>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof generateCourse>>,
  TError,
  { data: UserAnswerDto[] },
  TContext
> => {
  const mutationKey = ['generateCourse'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof generateCourse>>,
    { data: UserAnswerDto[] }
  > = (props) => {
    const { data } = props ?? {};

    return generateCourse(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type GenerateCourseMutationResult = NonNullable<Awaited<ReturnType<typeof generateCourse>>>;
export type GenerateCourseMutationBody = UserAnswerDto[];
export type GenerateCourseMutationError = unknown;

/**
 * @summary 生成課程
 */
export const useGenerateCourse = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof generateCourse>>,
      TError,
      { data: UserAnswerDto[] },
      TContext
    >;
    request?: SecondParameter<typeof customInstant>;
  },
  queryClient?: QueryClient
): UseMutationReturnType<
  Awaited<ReturnType<typeof generateCourse>>,
  TError,
  { data: UserAnswerDto[] },
  TContext
> => {
  const mutationOptions = getGenerateCourseMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * 生成章節
 * @summary 生成章節
 */
export const generateChapter = (
  userChapterDto: MaybeRef<UserChapterDto>,
  options?: SecondParameter<typeof customInstant>,
  signal?: AbortSignal
) => {
  userChapterDto = unref(userChapterDto);

  return customInstant<void>(
    {
      url: `/api/v1/generate/chapter`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: userChapterDto,
      signal,
    },
    options
  );
};

export const getGenerateChapterMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof generateChapter>>,
    TError,
    { data: UserChapterDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstant>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof generateChapter>>,
  TError,
  { data: UserChapterDto },
  TContext
> => {
  const mutationKey = ['generateChapter'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof generateChapter>>,
    { data: UserChapterDto }
  > = (props) => {
    const { data } = props ?? {};

    return generateChapter(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type GenerateChapterMutationResult = NonNullable<
  Awaited<ReturnType<typeof generateChapter>>
>;
export type GenerateChapterMutationBody = UserChapterDto;
export type GenerateChapterMutationError = unknown;

/**
 * @summary 生成章節
 */
export const useGenerateChapter = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof generateChapter>>,
      TError,
      { data: UserChapterDto },
      TContext
    >;
    request?: SecondParameter<typeof customInstant>;
  },
  queryClient?: QueryClient
): UseMutationReturnType<
  Awaited<ReturnType<typeof generateChapter>>,
  TError,
  { data: UserChapterDto },
  TContext
> => {
  const mutationOptions = getGenerateChapterMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * 上傳圖片並返回UUID
 * @summary 上傳圖片
 */
export const uploadFile = (
  uploadFileBody: MaybeRef<UploadFileBody>,
  options?: SecondParameter<typeof customInstant>,
  signal?: AbortSignal
) => {
  uploadFileBody = unref(uploadFileBody);

  return customInstant<FileUploadResponse>(
    {
      url: `/api/v1/files/upload`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: uploadFileBody,
      signal,
    },
    options
  );
};

export const getUploadFileMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof uploadFile>>,
    TError,
    { data: UploadFileBody },
    TContext
  >;
  request?: SecondParameter<typeof customInstant>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof uploadFile>>,
  TError,
  { data: UploadFileBody },
  TContext
> => {
  const mutationKey = ['uploadFile'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof uploadFile>>,
    { data: UploadFileBody }
  > = (props) => {
    const { data } = props ?? {};

    return uploadFile(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UploadFileMutationResult = NonNullable<Awaited<ReturnType<typeof uploadFile>>>;
export type UploadFileMutationBody = UploadFileBody;
export type UploadFileMutationError = unknown;

/**
 * @summary 上傳圖片
 */
export const useUploadFile = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof uploadFile>>,
      TError,
      { data: UploadFileBody },
      TContext
    >;
    request?: SecondParameter<typeof customInstant>;
  },
  queryClient?: QueryClient
): UseMutationReturnType<
  Awaited<ReturnType<typeof uploadFile>>,
  TError,
  { data: UploadFileBody },
  TContext
> => {
  const mutationOptions = getUploadFileMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * 取得所有報名的列表
 * @summary 取得所有綁定
 */
export const getAllEnrollments = (
  options?: SecondParameter<typeof customInstant>,
  signal?: AbortSignal
) => {
  return customInstant<EnrollmentDto[]>(
    { url: `/api/v1/enrollments`, method: 'GET', signal },
    options
  );
};

export const getGetAllEnrollmentsQueryKey = () => {
  return ['api', 'v1', 'enrollments'] as const;
};

export const getGetAllEnrollmentsQueryOptions = <
  TData = Awaited<ReturnType<typeof getAllEnrollments>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllEnrollments>>, TError, TData>>;
  request?: SecondParameter<typeof customInstant>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetAllEnrollmentsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllEnrollments>>> = ({ signal }) =>
    getAllEnrollments(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAllEnrollments>>,
    TError,
    TData
  >;
};

export type GetAllEnrollmentsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAllEnrollments>>
>;
export type GetAllEnrollmentsQueryError = unknown;

/**
 * @summary 取得所有綁定
 */

export function useGetAllEnrollments<
  TData = Awaited<ReturnType<typeof getAllEnrollments>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllEnrollments>>, TError, TData>>;
    request?: SecondParameter<typeof customInstant>;
  },
  queryClient?: QueryClient
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetAllEnrollmentsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}

/**
 * 課程綁定學生
 * @summary 課程綁定學生
 */
export const createEnrollment = (
  enrollmentDto: MaybeRef<EnrollmentDto>,
  options?: SecondParameter<typeof customInstant>,
  signal?: AbortSignal
) => {
  enrollmentDto = unref(enrollmentDto);

  return customInstant<EnrollmentDto>(
    {
      url: `/api/v1/enrollments`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: enrollmentDto,
      signal,
    },
    options
  );
};

export const getCreateEnrollmentMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createEnrollment>>,
    TError,
    { data: EnrollmentDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstant>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createEnrollment>>,
  TError,
  { data: EnrollmentDto },
  TContext
> => {
  const mutationKey = ['createEnrollment'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createEnrollment>>,
    { data: EnrollmentDto }
  > = (props) => {
    const { data } = props ?? {};

    return createEnrollment(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateEnrollmentMutationResult = NonNullable<
  Awaited<ReturnType<typeof createEnrollment>>
>;
export type CreateEnrollmentMutationBody = EnrollmentDto;
export type CreateEnrollmentMutationError = unknown;

/**
 * @summary 課程綁定學生
 */
export const useCreateEnrollment = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createEnrollment>>,
      TError,
      { data: EnrollmentDto },
      TContext
    >;
    request?: SecondParameter<typeof customInstant>;
  },
  queryClient?: QueryClient
): UseMutationReturnType<
  Awaited<ReturnType<typeof createEnrollment>>,
  TError,
  { data: EnrollmentDto },
  TContext
> => {
  const mutationOptions = getCreateEnrollmentMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * 取得所有課程的列表
 * @summary 取得所有課程
 */
export const getAllCourses = (
  options?: SecondParameter<typeof customInstant>,
  signal?: AbortSignal
) => {
  return customInstant<CourseDto[]>({ url: `/api/v1/courses`, method: 'GET', signal }, options);
};

export const getGetAllCoursesQueryKey = () => {
  return ['api', 'v1', 'courses'] as const;
};

export const getGetAllCoursesQueryOptions = <
  TData = Awaited<ReturnType<typeof getAllCourses>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllCourses>>, TError, TData>>;
  request?: SecondParameter<typeof customInstant>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetAllCoursesQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllCourses>>> = ({ signal }) =>
    getAllCourses(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAllCourses>>,
    TError,
    TData
  >;
};

export type GetAllCoursesQueryResult = NonNullable<Awaited<ReturnType<typeof getAllCourses>>>;
export type GetAllCoursesQueryError = unknown;

/**
 * @summary 取得所有課程
 */

export function useGetAllCourses<
  TData = Awaited<ReturnType<typeof getAllCourses>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllCourses>>, TError, TData>>;
    request?: SecondParameter<typeof customInstant>;
  },
  queryClient?: QueryClient
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetAllCoursesQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}

/**
 * 建立新的課程
 * @summary 新增課程
 */
export const createCourse = (
  courseDto: MaybeRef<CourseDto>,
  options?: SecondParameter<typeof customInstant>,
  signal?: AbortSignal
) => {
  courseDto = unref(courseDto);

  return customInstant<CourseDto>(
    {
      url: `/api/v1/courses`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: courseDto,
      signal,
    },
    options
  );
};

export const getCreateCourseMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createCourse>>,
    TError,
    { data: CourseDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstant>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createCourse>>,
  TError,
  { data: CourseDto },
  TContext
> => {
  const mutationKey = ['createCourse'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createCourse>>,
    { data: CourseDto }
  > = (props) => {
    const { data } = props ?? {};

    return createCourse(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateCourseMutationResult = NonNullable<Awaited<ReturnType<typeof createCourse>>>;
export type CreateCourseMutationBody = CourseDto;
export type CreateCourseMutationError = unknown;

/**
 * @summary 新增課程
 */
export const useCreateCourse = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createCourse>>,
      TError,
      { data: CourseDto },
      TContext
    >;
    request?: SecondParameter<typeof customInstant>;
  },
  queryClient?: QueryClient
): UseMutationReturnType<
  Awaited<ReturnType<typeof createCourse>>,
  TError,
  { data: CourseDto },
  TContext
> => {
  const mutationOptions = getCreateCourseMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * 根據課程ID取得包含所有單元和章節的完整課程資訊
 * @summary 依ID建立課程詳細資訊
 */
export const createCourseDetail = (
  courseDetailDto: MaybeRef<CourseDetailDto>,
  options?: SecondParameter<typeof customInstant>,
  signal?: AbortSignal
) => {
  courseDetailDto = unref(courseDetailDto);

  return customInstant<CourseDetailDto>(
    {
      url: `/api/v1/courses/detail`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: courseDetailDto,
      signal,
    },
    options
  );
};

export const getCreateCourseDetailMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createCourseDetail>>,
    TError,
    { data: CourseDetailDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstant>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createCourseDetail>>,
  TError,
  { data: CourseDetailDto },
  TContext
> => {
  const mutationKey = ['createCourseDetail'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createCourseDetail>>,
    { data: CourseDetailDto }
  > = (props) => {
    const { data } = props ?? {};

    return createCourseDetail(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateCourseDetailMutationResult = NonNullable<
  Awaited<ReturnType<typeof createCourseDetail>>
>;
export type CreateCourseDetailMutationBody = CourseDetailDto;
export type CreateCourseDetailMutationError = unknown;

/**
 * @summary 依ID建立課程詳細資訊
 */
export const useCreateCourseDetail = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createCourseDetail>>,
      TError,
      { data: CourseDetailDto },
      TContext
    >;
    request?: SecondParameter<typeof customInstant>;
  },
  queryClient?: QueryClient
): UseMutationReturnType<
  Awaited<ReturnType<typeof createCourseDetail>>,
  TError,
  { data: CourseDetailDto },
  TContext
> => {
  const mutationOptions = getCreateCourseDetailMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * 建立新的課程章節
 * @summary 新增章節
 */
export const createChapter = (
  chapterDto: MaybeRef<ChapterDto>,
  options?: SecondParameter<typeof customInstant>,
  signal?: AbortSignal
) => {
  chapterDto = unref(chapterDto);

  return customInstant<ChapterDto>(
    {
      url: `/api/v1/chapters`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: chapterDto,
      signal,
    },
    options
  );
};

export const getCreateChapterMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createChapter>>,
    TError,
    { data: ChapterDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstant>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createChapter>>,
  TError,
  { data: ChapterDto },
  TContext
> => {
  const mutationKey = ['createChapter'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createChapter>>,
    { data: ChapterDto }
  > = (props) => {
    const { data } = props ?? {};

    return createChapter(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateChapterMutationResult = NonNullable<Awaited<ReturnType<typeof createChapter>>>;
export type CreateChapterMutationBody = ChapterDto;
export type CreateChapterMutationError = unknown;

/**
 * @summary 新增章節
 */
export const useCreateChapter = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createChapter>>,
      TError,
      { data: ChapterDto },
      TContext
    >;
    request?: SecondParameter<typeof customInstant>;
  },
  queryClient?: QueryClient
): UseMutationReturnType<
  Awaited<ReturnType<typeof createChapter>>,
  TError,
  { data: ChapterDto },
  TContext
> => {
  const mutationOptions = getCreateChapterMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * 取得所有使用者的列表
 * @summary 取得所有使用者
 */
export const getAllUsers = (
  options?: SecondParameter<typeof customInstant>,
  signal?: AbortSignal
) => {
  return customInstant<UserInfoDto[]>({ url: `/api/v1/users`, method: 'GET', signal }, options);
};

export const getGetAllUsersQueryKey = () => {
  return ['api', 'v1', 'users'] as const;
};

export const getGetAllUsersQueryOptions = <
  TData = Awaited<ReturnType<typeof getAllUsers>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllUsers>>, TError, TData>>;
  request?: SecondParameter<typeof customInstant>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetAllUsersQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllUsers>>> = ({ signal }) =>
    getAllUsers(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAllUsers>>,
    TError,
    TData
  >;
};

export type GetAllUsersQueryResult = NonNullable<Awaited<ReturnType<typeof getAllUsers>>>;
export type GetAllUsersQueryError = unknown;

/**
 * @summary 取得所有使用者
 */

export function useGetAllUsers<TData = Awaited<ReturnType<typeof getAllUsers>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllUsers>>, TError, TData>>;
    request?: SecondParameter<typeof customInstant>;
  },
  queryClient?: QueryClient
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetAllUsersQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}

/**
 * 根據使用者Sub取得使用者詳細資訊
 * @summary 依Sub取得使用者
 */
export const getUserBySub = (
  sub: MaybeRef<string>,
  options?: SecondParameter<typeof customInstant>,
  signal?: AbortSignal
) => {
  sub = unref(sub);

  return customInstant<UserInfoDto>(
    { url: `/api/v1/users/${encodeURIComponent(String(sub))}`, method: 'GET', signal },
    options
  );
};

export const getGetUserBySubQueryKey = (sub?: MaybeRef<string>) => {
  return ['api', 'v1', 'users', sub] as const;
};

export const getGetUserBySubQueryOptions = <
  TData = Awaited<ReturnType<typeof getUserBySub>>,
  TError = unknown,
>(
  sub: MaybeRef<string>,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserBySub>>, TError, TData>>;
    request?: SecondParameter<typeof customInstant>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetUserBySubQueryKey(sub);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserBySub>>> = ({ signal }) =>
    getUserBySub(sub, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!unref(sub)),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getUserBySub>>, TError, TData>;
};

export type GetUserBySubQueryResult = NonNullable<Awaited<ReturnType<typeof getUserBySub>>>;
export type GetUserBySubQueryError = unknown;

/**
 * @summary 依Sub取得使用者
 */

export function useGetUserBySub<TData = Awaited<ReturnType<typeof getUserBySub>>, TError = unknown>(
  sub: MaybeRef<string>,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserBySub>>, TError, TData>>;
    request?: SecondParameter<typeof customInstant>;
  },
  queryClient?: QueryClient
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetUserBySubQueryOptions(sub, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}

/**
 * 根據使用者Sub刪除使用者
 * @summary 刪除使用者
 */
export const deleteUser = (
  sub: MaybeRef<string>,
  options?: SecondParameter<typeof customInstant>
) => {
  sub = unref(sub);

  return customInstant<void>(
    { url: `/api/v1/users/${encodeURIComponent(String(sub))}`, method: 'DELETE' },
    options
  );
};

export const getDeleteUserMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteUser>>,
    TError,
    { sub: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstant>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteUser>>,
  TError,
  { sub: string },
  TContext
> => {
  const mutationKey = ['deleteUser'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteUser>>, { sub: string }> = (
    props
  ) => {
    const { sub } = props ?? {};

    return deleteUser(sub, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteUserMutationResult = NonNullable<Awaited<ReturnType<typeof deleteUser>>>;

export type DeleteUserMutationError = unknown;

/**
 * @summary 刪除使用者
 */
export const useDeleteUser = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteUser>>,
      TError,
      { sub: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstant>;
  },
  queryClient?: QueryClient
): UseMutationReturnType<
  Awaited<ReturnType<typeof deleteUser>>,
  TError,
  { sub: string },
  TContext
> => {
  const mutationOptions = getDeleteUserMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * 根據課程ID取得所有單元列表
 * @summary 取得課程的所有單元
 */
export const getSectionsByCourseId = (
  courseId: MaybeRef<number>,
  options?: SecondParameter<typeof customInstant>,
  signal?: AbortSignal
) => {
  courseId = unref(courseId);

  return customInstant<SectionDto[]>(
    {
      url: `/api/v1/sections/course/${encodeURIComponent(String(courseId))}`,
      method: 'GET',
      signal,
    },
    options
  );
};

export const getGetSectionsByCourseIdQueryKey = (courseId?: MaybeRef<number>) => {
  return ['api', 'v1', 'sections', 'course', courseId] as const;
};

export const getGetSectionsByCourseIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getSectionsByCourseId>>,
  TError = unknown,
>(
  courseId: MaybeRef<number>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSectionsByCourseId>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstant>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetSectionsByCourseIdQueryKey(courseId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getSectionsByCourseId>>> = ({ signal }) =>
    getSectionsByCourseId(courseId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!unref(courseId)),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getSectionsByCourseId>>, TError, TData>;
};

export type GetSectionsByCourseIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSectionsByCourseId>>
>;
export type GetSectionsByCourseIdQueryError = unknown;

/**
 * @summary 取得課程的所有單元
 */

export function useGetSectionsByCourseId<
  TData = Awaited<ReturnType<typeof getSectionsByCourseId>>,
  TError = unknown,
>(
  courseId: MaybeRef<number>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSectionsByCourseId>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstant>;
  },
  queryClient?: QueryClient
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetSectionsByCourseIdQueryOptions(courseId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}

export const health = (options?: SecondParameter<typeof customInstant>, signal?: AbortSignal) => {
  return customInstant<string>({ url: `/api/v1/health`, method: 'GET', signal }, options);
};

export const getHealthQueryKey = () => {
  return ['api', 'v1', 'health'] as const;
};

export const getHealthQueryOptions = <
  TData = Awaited<ReturnType<typeof health>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof health>>, TError, TData>>;
  request?: SecondParameter<typeof customInstant>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getHealthQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof health>>> = ({ signal }) =>
    health(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof health>>,
    TError,
    TData
  >;
};

export type HealthQueryResult = NonNullable<Awaited<ReturnType<typeof health>>>;
export type HealthQueryError = unknown;

export function useHealth<TData = Awaited<ReturnType<typeof health>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof health>>, TError, TData>>;
    request?: SecondParameter<typeof customInstant>;
  },
  queryClient?: QueryClient
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getHealthQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}

/**
 * 根據UUID下載圖片
 * @summary 下載圖片
 */
export const downloadFile = (
  uuid: MaybeRef<string>,
  options?: SecondParameter<typeof customInstant>,
  signal?: AbortSignal
) => {
  uuid = unref(uuid);

  return customInstant<Blob>(
    {
      url: `/api/v1/files/${encodeURIComponent(String(uuid))}`,
      method: 'GET',
      responseType: 'blob',
      signal,
    },
    options
  );
};

export const getDownloadFileQueryKey = (uuid?: MaybeRef<string>) => {
  return ['api', 'v1', 'files', uuid] as const;
};

export const getDownloadFileQueryOptions = <
  TData = Awaited<ReturnType<typeof downloadFile>>,
  TError = unknown,
>(
  uuid: MaybeRef<string>,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadFile>>, TError, TData>>;
    request?: SecondParameter<typeof customInstant>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getDownloadFileQueryKey(uuid);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof downloadFile>>> = ({ signal }) =>
    downloadFile(uuid, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!unref(uuid)),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof downloadFile>>, TError, TData>;
};

export type DownloadFileQueryResult = NonNullable<Awaited<ReturnType<typeof downloadFile>>>;
export type DownloadFileQueryError = unknown;

/**
 * @summary 下載圖片
 */

export function useDownloadFile<TData = Awaited<ReturnType<typeof downloadFile>>, TError = unknown>(
  uuid: MaybeRef<string>,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadFile>>, TError, TData>>;
    request?: SecondParameter<typeof customInstant>;
  },
  queryClient?: QueryClient
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getDownloadFileQueryOptions(uuid, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}

/**
 * 獲取當前使用者的綁定
 * @summary 獲取當前使用者的綁定
 */
export const getCurrentUserEnrollments = (
  options?: SecondParameter<typeof customInstant>,
  signal?: AbortSignal
) => {
  return customInstant<EnrollmentDto[]>(
    { url: `/api/v1/enrollments/current`, method: 'GET', signal },
    options
  );
};

export const getGetCurrentUserEnrollmentsQueryKey = () => {
  return ['api', 'v1', 'enrollments', 'current'] as const;
};

export const getGetCurrentUserEnrollmentsQueryOptions = <
  TData = Awaited<ReturnType<typeof getCurrentUserEnrollments>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getCurrentUserEnrollments>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstant>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetCurrentUserEnrollmentsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCurrentUserEnrollments>>> = ({
    signal,
  }) => getCurrentUserEnrollments(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getCurrentUserEnrollments>>,
    TError,
    TData
  >;
};

export type GetCurrentUserEnrollmentsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCurrentUserEnrollments>>
>;
export type GetCurrentUserEnrollmentsQueryError = unknown;

/**
 * @summary 獲取當前使用者的綁定
 */

export function useGetCurrentUserEnrollments<
  TData = Awaited<ReturnType<typeof getCurrentUserEnrollments>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCurrentUserEnrollments>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstant>;
  },
  queryClient?: QueryClient
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetCurrentUserEnrollmentsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}

/**
 * 根據課程ID取得包含所有單元和章節的完整課程資訊
 * @summary 依ID取得課程詳細資訊（包含單元和章節）
 */
export const getCourseDetailById = (
  id: MaybeRef<number>,
  options?: SecondParameter<typeof customInstant>,
  signal?: AbortSignal
) => {
  id = unref(id);

  return customInstant<CourseDetailDto>(
    { url: `/api/v1/courses/${encodeURIComponent(String(id))}/detail`, method: 'GET', signal },
    options
  );
};

export const getGetCourseDetailByIdQueryKey = (id?: MaybeRef<number>) => {
  return ['api', 'v1', 'courses', id, 'detail'] as const;
};

export const getGetCourseDetailByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getCourseDetailById>>,
  TError = unknown,
>(
  id: MaybeRef<number>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCourseDetailById>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstant>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetCourseDetailByIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCourseDetailById>>> = ({ signal }) =>
    getCourseDetailById(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!unref(id)),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getCourseDetailById>>, TError, TData>;
};

export type GetCourseDetailByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCourseDetailById>>
>;
export type GetCourseDetailByIdQueryError = unknown;

/**
 * @summary 依ID取得課程詳細資訊（包含單元和章節）
 */

export function useGetCourseDetailById<
  TData = Awaited<ReturnType<typeof getCourseDetailById>>,
  TError = unknown,
>(
  id: MaybeRef<number>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCourseDetailById>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstant>;
  },
  queryClient?: QueryClient
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetCourseDetailByIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}

/**
 * 根據教師ID取得教師所授的課程
 * @summary 依教師ID取得課程
 */
export const getCoursesByTeacherId = (
  teacherId: MaybeRef<string>,
  options?: SecondParameter<typeof customInstant>,
  signal?: AbortSignal
) => {
  teacherId = unref(teacherId);

  return customInstant<CourseDto[]>(
    {
      url: `/api/v1/courses/teacher/${encodeURIComponent(String(teacherId))}`,
      method: 'GET',
      signal,
    },
    options
  );
};

export const getGetCoursesByTeacherIdQueryKey = (teacherId?: MaybeRef<string>) => {
  return ['api', 'v1', 'courses', 'teacher', teacherId] as const;
};

export const getGetCoursesByTeacherIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getCoursesByTeacherId>>,
  TError = unknown,
>(
  teacherId: MaybeRef<string>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCoursesByTeacherId>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstant>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetCoursesByTeacherIdQueryKey(teacherId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCoursesByTeacherId>>> = ({ signal }) =>
    getCoursesByTeacherId(teacherId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!unref(teacherId)),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getCoursesByTeacherId>>, TError, TData>;
};

export type GetCoursesByTeacherIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCoursesByTeacherId>>
>;
export type GetCoursesByTeacherIdQueryError = unknown;

/**
 * @summary 依教師ID取得課程
 */

export function useGetCoursesByTeacherId<
  TData = Awaited<ReturnType<typeof getCoursesByTeacherId>>,
  TError = unknown,
>(
  teacherId: MaybeRef<string>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCoursesByTeacherId>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstant>;
  },
  queryClient?: QueryClient
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetCoursesByTeacherIdQueryOptions(teacherId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}

/**
 * 取得當前用戶已選的課程
 * @summary 取得當前用戶已選的課程
 */
export const getSelectedCourses = (
  options?: SecondParameter<typeof customInstant>,
  signal?: AbortSignal
) => {
  return customInstant<CourseDto[]>(
    { url: `/api/v1/courses/select`, method: 'GET', signal },
    options
  );
};

export const getGetSelectedCoursesQueryKey = () => {
  return ['api', 'v1', 'courses', 'select'] as const;
};

export const getGetSelectedCoursesQueryOptions = <
  TData = Awaited<ReturnType<typeof getSelectedCourses>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSelectedCourses>>, TError, TData>>;
  request?: SecondParameter<typeof customInstant>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetSelectedCoursesQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getSelectedCourses>>> = ({ signal }) =>
    getSelectedCourses(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getSelectedCourses>>,
    TError,
    TData
  >;
};

export type GetSelectedCoursesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSelectedCourses>>
>;
export type GetSelectedCoursesQueryError = unknown;

/**
 * @summary 取得當前用戶已選的課程
 */

export function useGetSelectedCourses<
  TData = Awaited<ReturnType<typeof getSelectedCourses>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSelectedCourses>>, TError, TData>>;
    request?: SecondParameter<typeof customInstant>;
  },
  queryClient?: QueryClient
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetSelectedCoursesQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}

/**
 * 取得當前用戶開設課程
 * @summary 取得當前用戶開設課程
 */
export const getCurrentCourses = (
  options?: SecondParameter<typeof customInstant>,
  signal?: AbortSignal
) => {
  return customInstant<CourseDto[]>(
    { url: `/api/v1/courses/current`, method: 'GET', signal },
    options
  );
};

export const getGetCurrentCoursesQueryKey = () => {
  return ['api', 'v1', 'courses', 'current'] as const;
};

export const getGetCurrentCoursesQueryOptions = <
  TData = Awaited<ReturnType<typeof getCurrentCourses>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentCourses>>, TError, TData>>;
  request?: SecondParameter<typeof customInstant>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetCurrentCoursesQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCurrentCourses>>> = ({ signal }) =>
    getCurrentCourses(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getCurrentCourses>>,
    TError,
    TData
  >;
};

export type GetCurrentCoursesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCurrentCourses>>
>;
export type GetCurrentCoursesQueryError = unknown;

/**
 * @summary 取得當前用戶開設課程
 */

export function useGetCurrentCourses<
  TData = Awaited<ReturnType<typeof getCurrentCourses>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentCourses>>, TError, TData>>;
    request?: SecondParameter<typeof customInstant>;
  },
  queryClient?: QueryClient
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetCurrentCoursesQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}

/**
 * 根據單元ID取得所有章節列表
 * @summary 取得單元的所有章節
 */
export const getChaptersBySectionId = (
  sectionId: MaybeRef<number>,
  options?: SecondParameter<typeof customInstant>,
  signal?: AbortSignal
) => {
  sectionId = unref(sectionId);

  return customInstant<ChapterDto[]>(
    {
      url: `/api/v1/chapters/section/${encodeURIComponent(String(sectionId))}`,
      method: 'GET',
      signal,
    },
    options
  );
};

export const getGetChaptersBySectionIdQueryKey = (sectionId?: MaybeRef<number>) => {
  return ['api', 'v1', 'chapters', 'section', sectionId] as const;
};

export const getGetChaptersBySectionIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getChaptersBySectionId>>,
  TError = unknown,
>(
  sectionId: MaybeRef<number>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getChaptersBySectionId>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstant>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetChaptersBySectionIdQueryKey(sectionId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getChaptersBySectionId>>> = ({ signal }) =>
    getChaptersBySectionId(sectionId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!unref(sectionId)),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getChaptersBySectionId>>, TError, TData>;
};

export type GetChaptersBySectionIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getChaptersBySectionId>>
>;
export type GetChaptersBySectionIdQueryError = unknown;

/**
 * @summary 取得單元的所有章節
 */

export function useGetChaptersBySectionId<
  TData = Awaited<ReturnType<typeof getChaptersBySectionId>>,
  TError = unknown,
>(
  sectionId: MaybeRef<number>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getChaptersBySectionId>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstant>;
  },
  queryClient?: QueryClient
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetChaptersBySectionIdQueryOptions(sectionId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}
