/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import { customInstant } from './base/BaseApi';
import type { CourseDto, EnrollmentCreateRequest, EnrollmentResponse, UserInfoDto } from './model';
import { useMutation, useQuery } from '@tanstack/vue-query';
import type {
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType,
} from '@tanstack/vue-query';
import { computed, unref } from 'vue';
import type { MaybeRef } from 'vue';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 根據課程ID取得課程詳細資訊
 * @summary 依ID取得課程
 */
export const getCourseById = (
  id: MaybeRef<number>,
  options?: SecondParameter<typeof customInstant>,
  signal?: AbortSignal
) => {
  id = unref(id);

  return customInstant<CourseDto>(
    { url: `/api/v1/courses/${encodeURIComponent(String(id))}`, method: 'GET', signal },
    options
  );
};

export const getGetCourseByIdQueryKey = (id?: MaybeRef<number>) => {
  return ['api', 'v1', 'courses', id] as const;
};

export const getGetCourseByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getCourseById>>,
  TError = unknown,
>(
  id: MaybeRef<number>,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCourseById>>, TError, TData>>;
    request?: SecondParameter<typeof customInstant>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetCourseByIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCourseById>>> = ({ signal }) =>
    getCourseById(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!unref(id)),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getCourseById>>, TError, TData>;
};

export type GetCourseByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getCourseById>>>;
export type GetCourseByIdQueryError = unknown;

/**
 * @summary 依ID取得課程
 */

export function useGetCourseById<
  TData = Awaited<ReturnType<typeof getCourseById>>,
  TError = unknown,
>(
  id: MaybeRef<number>,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCourseById>>, TError, TData>>;
    request?: SecondParameter<typeof customInstant>;
  },
  queryClient?: QueryClient
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetCourseByIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}

/**
 * 根據課程ID更新課程資訊
 * @summary 更新課程
 */
export const updateCourse = (
  id: MaybeRef<number>,
  courseDto: MaybeRef<CourseDto>,
  options?: SecondParameter<typeof customInstant>
) => {
  id = unref(id);
  courseDto = unref(courseDto);

  return customInstant<CourseDto>(
    {
      url: `/api/v1/courses/${encodeURIComponent(String(id))}`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: courseDto,
    },
    options
  );
};

export const getUpdateCourseMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateCourse>>,
    TError,
    { id: number; data: CourseDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstant>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateCourse>>,
  TError,
  { id: number; data: CourseDto },
  TContext
> => {
  const mutationKey = ['updateCourse'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateCourse>>,
    { id: number; data: CourseDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateCourse(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateCourseMutationResult = NonNullable<Awaited<ReturnType<typeof updateCourse>>>;
export type UpdateCourseMutationBody = CourseDto;
export type UpdateCourseMutationError = unknown;

/**
 * @summary 更新課程
 */
export const useUpdateCourse = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateCourse>>,
      TError,
      { id: number; data: CourseDto },
      TContext
    >;
    request?: SecondParameter<typeof customInstant>;
  },
  queryClient?: QueryClient
): UseMutationReturnType<
  Awaited<ReturnType<typeof updateCourse>>,
  TError,
  { id: number; data: CourseDto },
  TContext
> => {
  const mutationOptions = getUpdateCourseMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * 根據課程ID刪除課程
 * @summary 刪除課程
 */
export const deleteCourse = (
  id: MaybeRef<number>,
  options?: SecondParameter<typeof customInstant>
) => {
  id = unref(id);

  return customInstant<void>(
    { url: `/api/v1/courses/${encodeURIComponent(String(id))}`, method: 'DELETE' },
    options
  );
};

export const getDeleteCourseMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteCourse>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customInstant>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteCourse>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ['deleteCourse'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteCourse>>, { id: number }> = (
    props
  ) => {
    const { id } = props ?? {};

    return deleteCourse(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteCourseMutationResult = NonNullable<Awaited<ReturnType<typeof deleteCourse>>>;

export type DeleteCourseMutationError = unknown;

/**
 * @summary 刪除課程
 */
export const useDeleteCourse = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteCourse>>,
      TError,
      { id: number },
      TContext
    >;
    request?: SecondParameter<typeof customInstant>;
  },
  queryClient?: QueryClient
): UseMutationReturnType<
  Awaited<ReturnType<typeof deleteCourse>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions = getDeleteCourseMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * 取得所有報名的列表
 * @summary 取得所有報名
 */
export const getAllEnrollments = (
  options?: SecondParameter<typeof customInstant>,
  signal?: AbortSignal
) => {
  return customInstant<EnrollmentResponse[]>(
    { url: `/api/v1/enrollments`, method: 'GET', signal },
    options
  );
};

export const getGetAllEnrollmentsQueryKey = () => {
  return ['api', 'v1', 'enrollments'] as const;
};

export const getGetAllEnrollmentsQueryOptions = <
  TData = Awaited<ReturnType<typeof getAllEnrollments>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllEnrollments>>, TError, TData>>;
  request?: SecondParameter<typeof customInstant>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetAllEnrollmentsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllEnrollments>>> = ({ signal }) =>
    getAllEnrollments(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAllEnrollments>>,
    TError,
    TData
  >;
};

export type GetAllEnrollmentsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAllEnrollments>>
>;
export type GetAllEnrollmentsQueryError = unknown;

/**
 * @summary 取得所有報名
 */

export function useGetAllEnrollments<
  TData = Awaited<ReturnType<typeof getAllEnrollments>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllEnrollments>>, TError, TData>>;
    request?: SecondParameter<typeof customInstant>;
  },
  queryClient?: QueryClient
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetAllEnrollmentsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}

/**
 * 選擇課程
 * @summary 選擇課程
 */
export const createEnrollment = (
  enrollmentCreateRequest: MaybeRef<EnrollmentCreateRequest>,
  options?: SecondParameter<typeof customInstant>,
  signal?: AbortSignal
) => {
  enrollmentCreateRequest = unref(enrollmentCreateRequest);

  return customInstant<EnrollmentResponse>(
    {
      url: `/api/v1/enrollments`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: enrollmentCreateRequest,
      signal,
    },
    options
  );
};

export const getCreateEnrollmentMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createEnrollment>>,
    TError,
    { data: EnrollmentCreateRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstant>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createEnrollment>>,
  TError,
  { data: EnrollmentCreateRequest },
  TContext
> => {
  const mutationKey = ['createEnrollment'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createEnrollment>>,
    { data: EnrollmentCreateRequest }
  > = (props) => {
    const { data } = props ?? {};

    return createEnrollment(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateEnrollmentMutationResult = NonNullable<
  Awaited<ReturnType<typeof createEnrollment>>
>;
export type CreateEnrollmentMutationBody = EnrollmentCreateRequest;
export type CreateEnrollmentMutationError = unknown;

/**
 * @summary 選擇課程
 */
export const useCreateEnrollment = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createEnrollment>>,
      TError,
      { data: EnrollmentCreateRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstant>;
  },
  queryClient?: QueryClient
): UseMutationReturnType<
  Awaited<ReturnType<typeof createEnrollment>>,
  TError,
  { data: EnrollmentCreateRequest },
  TContext
> => {
  const mutationOptions = getCreateEnrollmentMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * 取得所有課程的列表
 * @summary 取得所有課程
 */
export const getAllCourses = (
  options?: SecondParameter<typeof customInstant>,
  signal?: AbortSignal
) => {
  return customInstant<CourseDto[]>({ url: `/api/v1/courses`, method: 'GET', signal }, options);
};

export const getGetAllCoursesQueryKey = () => {
  return ['api', 'v1', 'courses'] as const;
};

export const getGetAllCoursesQueryOptions = <
  TData = Awaited<ReturnType<typeof getAllCourses>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllCourses>>, TError, TData>>;
  request?: SecondParameter<typeof customInstant>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetAllCoursesQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllCourses>>> = ({ signal }) =>
    getAllCourses(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAllCourses>>,
    TError,
    TData
  >;
};

export type GetAllCoursesQueryResult = NonNullable<Awaited<ReturnType<typeof getAllCourses>>>;
export type GetAllCoursesQueryError = unknown;

/**
 * @summary 取得所有課程
 */

export function useGetAllCourses<
  TData = Awaited<ReturnType<typeof getAllCourses>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllCourses>>, TError, TData>>;
    request?: SecondParameter<typeof customInstant>;
  },
  queryClient?: QueryClient
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetAllCoursesQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}

/**
 * 建立新的課程
 * @summary 新增課程
 */
export const createCourse = (
  courseDto: MaybeRef<CourseDto>,
  options?: SecondParameter<typeof customInstant>,
  signal?: AbortSignal
) => {
  courseDto = unref(courseDto);

  return customInstant<CourseDto>(
    {
      url: `/api/v1/courses`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: courseDto,
      signal,
    },
    options
  );
};

export const getCreateCourseMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createCourse>>,
    TError,
    { data: CourseDto },
    TContext
  >;
  request?: SecondParameter<typeof customInstant>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createCourse>>,
  TError,
  { data: CourseDto },
  TContext
> => {
  const mutationKey = ['createCourse'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createCourse>>,
    { data: CourseDto }
  > = (props) => {
    const { data } = props ?? {};

    return createCourse(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateCourseMutationResult = NonNullable<Awaited<ReturnType<typeof createCourse>>>;
export type CreateCourseMutationBody = CourseDto;
export type CreateCourseMutationError = unknown;

/**
 * @summary 新增課程
 */
export const useCreateCourse = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createCourse>>,
      TError,
      { data: CourseDto },
      TContext
    >;
    request?: SecondParameter<typeof customInstant>;
  },
  queryClient?: QueryClient
): UseMutationReturnType<
  Awaited<ReturnType<typeof createCourse>>,
  TError,
  { data: CourseDto },
  TContext
> => {
  const mutationOptions = getCreateCourseMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

export const hello = (options?: SecondParameter<typeof customInstant>, signal?: AbortSignal) => {
  return customInstant<string>({ url: `/api/v1`, method: 'GET', signal }, options);
};

export const getHelloQueryKey = () => {
  return ['api', 'v1'] as const;
};

export const getHelloQueryOptions = <
  TData = Awaited<ReturnType<typeof hello>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof hello>>, TError, TData>>;
  request?: SecondParameter<typeof customInstant>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getHelloQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof hello>>> = ({ signal }) =>
    hello(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof hello>>,
    TError,
    TData
  >;
};

export type HelloQueryResult = NonNullable<Awaited<ReturnType<typeof hello>>>;
export type HelloQueryError = unknown;

export function useHello<TData = Awaited<ReturnType<typeof hello>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof hello>>, TError, TData>>;
    request?: SecondParameter<typeof customInstant>;
  },
  queryClient?: QueryClient
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getHelloQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}

/**
 * 取得所有使用者的列表
 * @summary 取得所有使用者
 */
export const getAllUsers = (
  options?: SecondParameter<typeof customInstant>,
  signal?: AbortSignal
) => {
  return customInstant<UserInfoDto[]>({ url: `/api/v1/users`, method: 'GET', signal }, options);
};

export const getGetAllUsersQueryKey = () => {
  return ['api', 'v1', 'users'] as const;
};

export const getGetAllUsersQueryOptions = <
  TData = Awaited<ReturnType<typeof getAllUsers>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllUsers>>, TError, TData>>;
  request?: SecondParameter<typeof customInstant>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetAllUsersQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllUsers>>> = ({ signal }) =>
    getAllUsers(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAllUsers>>,
    TError,
    TData
  >;
};

export type GetAllUsersQueryResult = NonNullable<Awaited<ReturnType<typeof getAllUsers>>>;
export type GetAllUsersQueryError = unknown;

/**
 * @summary 取得所有使用者
 */

export function useGetAllUsers<TData = Awaited<ReturnType<typeof getAllUsers>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllUsers>>, TError, TData>>;
    request?: SecondParameter<typeof customInstant>;
  },
  queryClient?: QueryClient
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetAllUsersQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}

/**
 * 根據使用者Sub取得使用者詳細資訊
 * @summary 依Sub取得使用者
 */
export const getUserBySub = (
  sub: MaybeRef<string>,
  options?: SecondParameter<typeof customInstant>,
  signal?: AbortSignal
) => {
  sub = unref(sub);

  return customInstant<UserInfoDto>(
    { url: `/api/v1/users/${encodeURIComponent(String(sub))}`, method: 'GET', signal },
    options
  );
};

export const getGetUserBySubQueryKey = (sub?: MaybeRef<string>) => {
  return ['api', 'v1', 'users', sub] as const;
};

export const getGetUserBySubQueryOptions = <
  TData = Awaited<ReturnType<typeof getUserBySub>>,
  TError = unknown,
>(
  sub: MaybeRef<string>,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserBySub>>, TError, TData>>;
    request?: SecondParameter<typeof customInstant>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetUserBySubQueryKey(sub);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserBySub>>> = ({ signal }) =>
    getUserBySub(sub, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!unref(sub)),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getUserBySub>>, TError, TData>;
};

export type GetUserBySubQueryResult = NonNullable<Awaited<ReturnType<typeof getUserBySub>>>;
export type GetUserBySubQueryError = unknown;

/**
 * @summary 依Sub取得使用者
 */

export function useGetUserBySub<TData = Awaited<ReturnType<typeof getUserBySub>>, TError = unknown>(
  sub: MaybeRef<string>,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserBySub>>, TError, TData>>;
    request?: SecondParameter<typeof customInstant>;
  },
  queryClient?: QueryClient
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetUserBySubQueryOptions(sub, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}

/**
 * 根據使用者Sub刪除使用者
 * @summary 刪除使用者
 */
export const deleteUser = (
  sub: MaybeRef<string>,
  options?: SecondParameter<typeof customInstant>
) => {
  sub = unref(sub);

  return customInstant<void>(
    { url: `/api/v1/users/${encodeURIComponent(String(sub))}`, method: 'DELETE' },
    options
  );
};

export const getDeleteUserMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteUser>>,
    TError,
    { sub: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstant>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteUser>>,
  TError,
  { sub: string },
  TContext
> => {
  const mutationKey = ['deleteUser'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteUser>>, { sub: string }> = (
    props
  ) => {
    const { sub } = props ?? {};

    return deleteUser(sub, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteUserMutationResult = NonNullable<Awaited<ReturnType<typeof deleteUser>>>;

export type DeleteUserMutationError = unknown;

/**
 * @summary 刪除使用者
 */
export const useDeleteUser = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteUser>>,
      TError,
      { sub: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstant>;
  },
  queryClient?: QueryClient
): UseMutationReturnType<
  Awaited<ReturnType<typeof deleteUser>>,
  TError,
  { sub: string },
  TContext
> => {
  const mutationOptions = getDeleteUserMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * 根據使用者Email取得使用者詳細資訊
 * @summary 依Email取得使用者
 */
export const getUserByEmail = (
  email: MaybeRef<string>,
  options?: SecondParameter<typeof customInstant>,
  signal?: AbortSignal
) => {
  email = unref(email);

  return customInstant<UserInfoDto>(
    { url: `/api/v1/users/email/${encodeURIComponent(String(email))}`, method: 'GET', signal },
    options
  );
};

export const getGetUserByEmailQueryKey = (email?: MaybeRef<string>) => {
  return ['api', 'v1', 'users', 'email', email] as const;
};

export const getGetUserByEmailQueryOptions = <
  TData = Awaited<ReturnType<typeof getUserByEmail>>,
  TError = unknown,
>(
  email: MaybeRef<string>,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserByEmail>>, TError, TData>>;
    request?: SecondParameter<typeof customInstant>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetUserByEmailQueryKey(email);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserByEmail>>> = ({ signal }) =>
    getUserByEmail(email, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!unref(email)),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getUserByEmail>>, TError, TData>;
};

export type GetUserByEmailQueryResult = NonNullable<Awaited<ReturnType<typeof getUserByEmail>>>;
export type GetUserByEmailQueryError = unknown;

/**
 * @summary 依Email取得使用者
 */

export function useGetUserByEmail<
  TData = Awaited<ReturnType<typeof getUserByEmail>>,
  TError = unknown,
>(
  email: MaybeRef<string>,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserByEmail>>, TError, TData>>;
    request?: SecondParameter<typeof customInstant>;
  },
  queryClient?: QueryClient
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetUserByEmailQueryOptions(email, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}

export const helloUser = (
  options?: SecondParameter<typeof customInstant>,
  signal?: AbortSignal
) => {
  return customInstant<string>({ url: `/api/v1/user`, method: 'GET', signal }, options);
};

export const getHelloUserQueryKey = () => {
  return ['api', 'v1', 'user'] as const;
};

export const getHelloUserQueryOptions = <
  TData = Awaited<ReturnType<typeof helloUser>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof helloUser>>, TError, TData>>;
  request?: SecondParameter<typeof customInstant>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getHelloUserQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof helloUser>>> = ({ signal }) =>
    helloUser(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof helloUser>>,
    TError,
    TData
  >;
};

export type HelloUserQueryResult = NonNullable<Awaited<ReturnType<typeof helloUser>>>;
export type HelloUserQueryError = unknown;

export function useHelloUser<TData = Awaited<ReturnType<typeof helloUser>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof helloUser>>, TError, TData>>;
    request?: SecondParameter<typeof customInstant>;
  },
  queryClient?: QueryClient
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getHelloUserQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}

export const health = (options?: SecondParameter<typeof customInstant>, signal?: AbortSignal) => {
  return customInstant<string>({ url: `/api/v1/health`, method: 'GET', signal }, options);
};

export const getHealthQueryKey = () => {
  return ['api', 'v1', 'health'] as const;
};

export const getHealthQueryOptions = <
  TData = Awaited<ReturnType<typeof health>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof health>>, TError, TData>>;
  request?: SecondParameter<typeof customInstant>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getHealthQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof health>>> = ({ signal }) =>
    health(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof health>>,
    TError,
    TData
  >;
};

export type HealthQueryResult = NonNullable<Awaited<ReturnType<typeof health>>>;
export type HealthQueryError = unknown;

export function useHealth<TData = Awaited<ReturnType<typeof health>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof health>>, TError, TData>>;
    request?: SecondParameter<typeof customInstant>;
  },
  queryClient?: QueryClient
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getHealthQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}

/**
 * 根據報名ID取得報名詳細資訊
 * @summary 依ID取得報名
 */
export const getEnrollmentById = (
  id: MaybeRef<number>,
  options?: SecondParameter<typeof customInstant>,
  signal?: AbortSignal
) => {
  id = unref(id);

  return customInstant<EnrollmentResponse>(
    { url: `/api/v1/enrollments/${encodeURIComponent(String(id))}`, method: 'GET', signal },
    options
  );
};

export const getGetEnrollmentByIdQueryKey = (id?: MaybeRef<number>) => {
  return ['api', 'v1', 'enrollments', id] as const;
};

export const getGetEnrollmentByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getEnrollmentById>>,
  TError = unknown,
>(
  id: MaybeRef<number>,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getEnrollmentById>>, TError, TData>>;
    request?: SecondParameter<typeof customInstant>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetEnrollmentByIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getEnrollmentById>>> = ({ signal }) =>
    getEnrollmentById(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!unref(id)),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getEnrollmentById>>, TError, TData>;
};

export type GetEnrollmentByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getEnrollmentById>>
>;
export type GetEnrollmentByIdQueryError = unknown;

/**
 * @summary 依ID取得報名
 */

export function useGetEnrollmentById<
  TData = Awaited<ReturnType<typeof getEnrollmentById>>,
  TError = unknown,
>(
  id: MaybeRef<number>,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getEnrollmentById>>, TError, TData>>;
    request?: SecondParameter<typeof customInstant>;
  },
  queryClient?: QueryClient
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetEnrollmentByIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}

/**
 * 根據報名ID刪除報名
 * @summary 刪除報名
 */
export const deleteEnrollment = (
  id: MaybeRef<number>,
  options?: SecondParameter<typeof customInstant>
) => {
  id = unref(id);

  return customInstant<void>(
    { url: `/api/v1/enrollments/${encodeURIComponent(String(id))}`, method: 'DELETE' },
    options
  );
};

export const getDeleteEnrollmentMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteEnrollment>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customInstant>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteEnrollment>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ['deleteEnrollment'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteEnrollment>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return deleteEnrollment(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteEnrollmentMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteEnrollment>>
>;

export type DeleteEnrollmentMutationError = unknown;

/**
 * @summary 刪除報名
 */
export const useDeleteEnrollment = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteEnrollment>>,
      TError,
      { id: number },
      TContext
    >;
    request?: SecondParameter<typeof customInstant>;
  },
  queryClient?: QueryClient
): UseMutationReturnType<
  Awaited<ReturnType<typeof deleteEnrollment>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions = getDeleteEnrollmentMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * 根據學生ID取得學生的所有報名
 * @summary 依學生ID取得報名
 */
export const getEnrollmentsByStudentId = (
  studentId: MaybeRef<string>,
  options?: SecondParameter<typeof customInstant>,
  signal?: AbortSignal
) => {
  studentId = unref(studentId);

  return customInstant<EnrollmentResponse[]>(
    {
      url: `/api/v1/enrollments/student/${encodeURIComponent(String(studentId))}`,
      method: 'GET',
      signal,
    },
    options
  );
};

export const getGetEnrollmentsByStudentIdQueryKey = (studentId?: MaybeRef<string>) => {
  return ['api', 'v1', 'enrollments', 'student', studentId] as const;
};

export const getGetEnrollmentsByStudentIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getEnrollmentsByStudentId>>,
  TError = unknown,
>(
  studentId: MaybeRef<string>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getEnrollmentsByStudentId>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstant>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetEnrollmentsByStudentIdQueryKey(studentId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getEnrollmentsByStudentId>>> = ({
    signal,
  }) => getEnrollmentsByStudentId(studentId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!unref(studentId)),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getEnrollmentsByStudentId>>, TError, TData>;
};

export type GetEnrollmentsByStudentIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getEnrollmentsByStudentId>>
>;
export type GetEnrollmentsByStudentIdQueryError = unknown;

/**
 * @summary 依學生ID取得報名
 */

export function useGetEnrollmentsByStudentId<
  TData = Awaited<ReturnType<typeof getEnrollmentsByStudentId>>,
  TError = unknown,
>(
  studentId: MaybeRef<string>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getEnrollmentsByStudentId>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstant>;
  },
  queryClient?: QueryClient
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetEnrollmentsByStudentIdQueryOptions(studentId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}

/**
 * 根據課程ID取得課程的所有報名
 * @summary 依課程ID取得報名
 */
export const getEnrollmentsByCourseId = (
  courseId: MaybeRef<number>,
  options?: SecondParameter<typeof customInstant>,
  signal?: AbortSignal
) => {
  courseId = unref(courseId);

  return customInstant<EnrollmentResponse[]>(
    {
      url: `/api/v1/enrollments/course/${encodeURIComponent(String(courseId))}`,
      method: 'GET',
      signal,
    },
    options
  );
};

export const getGetEnrollmentsByCourseIdQueryKey = (courseId?: MaybeRef<number>) => {
  return ['api', 'v1', 'enrollments', 'course', courseId] as const;
};

export const getGetEnrollmentsByCourseIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getEnrollmentsByCourseId>>,
  TError = unknown,
>(
  courseId: MaybeRef<number>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getEnrollmentsByCourseId>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstant>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetEnrollmentsByCourseIdQueryKey(courseId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getEnrollmentsByCourseId>>> = ({
    signal,
  }) => getEnrollmentsByCourseId(courseId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!unref(courseId)),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getEnrollmentsByCourseId>>, TError, TData>;
};

export type GetEnrollmentsByCourseIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getEnrollmentsByCourseId>>
>;
export type GetEnrollmentsByCourseIdQueryError = unknown;

/**
 * @summary 依課程ID取得報名
 */

export function useGetEnrollmentsByCourseId<
  TData = Awaited<ReturnType<typeof getEnrollmentsByCourseId>>,
  TError = unknown,
>(
  courseId: MaybeRef<number>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getEnrollmentsByCourseId>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstant>;
  },
  queryClient?: QueryClient
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetEnrollmentsByCourseIdQueryOptions(courseId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}

/**
 * 根據教師ID取得教師所授的課程
 * @summary 依教師ID取得課程
 */
export const getCoursesByTeacherId = (
  teacherId: MaybeRef<string>,
  options?: SecondParameter<typeof customInstant>,
  signal?: AbortSignal
) => {
  teacherId = unref(teacherId);

  return customInstant<CourseDto[]>(
    {
      url: `/api/v1/courses/teacher/${encodeURIComponent(String(teacherId))}`,
      method: 'GET',
      signal,
    },
    options
  );
};

export const getGetCoursesByTeacherIdQueryKey = (teacherId?: MaybeRef<string>) => {
  return ['api', 'v1', 'courses', 'teacher', teacherId] as const;
};

export const getGetCoursesByTeacherIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getCoursesByTeacherId>>,
  TError = unknown,
>(
  teacherId: MaybeRef<string>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCoursesByTeacherId>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstant>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getGetCoursesByTeacherIdQueryKey(teacherId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCoursesByTeacherId>>> = ({ signal }) =>
    getCoursesByTeacherId(teacherId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!unref(teacherId)),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getCoursesByTeacherId>>, TError, TData>;
};

export type GetCoursesByTeacherIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCoursesByTeacherId>>
>;
export type GetCoursesByTeacherIdQueryError = unknown;

/**
 * @summary 依教師ID取得課程
 */

export function useGetCoursesByTeacherId<
  TData = Awaited<ReturnType<typeof getCoursesByTeacherId>>,
  TError = unknown,
>(
  teacherId: MaybeRef<string>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCoursesByTeacherId>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstant>;
  },
  queryClient?: QueryClient
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetCoursesByTeacherIdQueryOptions(teacherId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}

export const helloAdmin = (
  options?: SecondParameter<typeof customInstant>,
  signal?: AbortSignal
) => {
  return customInstant<string>({ url: `/api/v1/admin`, method: 'GET', signal }, options);
};

export const getHelloAdminQueryKey = () => {
  return ['api', 'v1', 'admin'] as const;
};

export const getHelloAdminQueryOptions = <
  TData = Awaited<ReturnType<typeof helloAdmin>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof helloAdmin>>, TError, TData>>;
  request?: SecondParameter<typeof customInstant>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = getHelloAdminQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof helloAdmin>>> = ({ signal }) =>
    helloAdmin(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof helloAdmin>>,
    TError,
    TData
  >;
};

export type HelloAdminQueryResult = NonNullable<Awaited<ReturnType<typeof helloAdmin>>>;
export type HelloAdminQueryError = unknown;

export function useHelloAdmin<TData = Awaited<ReturnType<typeof helloAdmin>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof helloAdmin>>, TError, TData>>;
    request?: SecondParameter<typeof customInstant>;
  },
  queryClient?: QueryClient
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getHelloAdminQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}
