# server.port=8040
spring.application.name=api
spring.datasource.url=jdbc:postgresql://172.16.1.26:30543/postgres?currentSchema=spring
spring.datasource.username=postgres
spring.datasource.password=example123456
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=spring
spring.data.jpa.repositories.bootstrap-mode=deferred
# hibernate ddl auto: none, validate, update, create, create-drop
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Spring Security OAuth2 Resource Server JWT settings
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://keycloak.yang-lin.dev/realms/iep
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://keycloak.yang-lin.dev/realms/iep/protocol/openid-connect/certs
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=DEBUG

jwt.auth.converter.resource-id=iep
jwt.auth.converter.principle-attribute=preferred_username

# Springdoc OpenAPI
springdoc.api-docs.path=/api/api-docs
springdoc.swagger-ui.path=/api/swagger-ui/index.html
springdoc.swagger-ui.operationsSorter=method

# Storage Configuration
app.upload-file.dir=./upload