services:
  mysql:
    image: mysql:8.0
    container_name: iep-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: bigred
      MYSQL_DATABASE: iep
    ports:
      - "3306:3306"
    volumes:
      - iep-mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - iep-network

  qdrant:
    image: qdrant/qdrant:latest
    container_name: iep-qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
    volumes:
      - qdrant-data:/qdrant/storage
    networks:
      - iep-network

  iep:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: iep-app
    restart: unless-stopped
    environment:
      TZ: Asia/Taipei
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/iep?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Taipei&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: bigred
      APP_GENERATE_URL: http://teachat:8081
    ports:
      - "8040:8040"
    volumes:
      - upload_data:/app/upload
    depends_on:
      teachat:
        condition: service_started
    networks:
      - iep-network

  teachat:
    build:
      context: ../teaChatBot
      dockerfile: Dockerfile
    container_name: iep-teachat
    restart: unless-stopped
    environment:
      TZ: Asia/Taipei
      GOOGLE_GEMINI_API_KEY: "your google gemini api key"
      GOOGLE_SEARCH_API_KEY: "your google search api key in GCP"
      GOOGLE_SEARCH_ENGINE_ID: "your google search engineID in GCP"
      QDRANT_URL: "http://qdrant:6333"
      QDRANT_COLLECTION_NAME: "knowledge"
      MYSQL_HOST: "mysql"
      MYSQL_PORT: "3306"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "bigred"
      MYSQL_DB: "iep"
      GEMINI_MODEL: "google ai model name"
      EMBEDDING_MODEL: "DMetaSoul/sbert-chinese-general-v2"
      WEB_API_URL: http://iep:8040
      THINKING_BUDGET: "-1"
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy
      qdrant:
        condition: service_started
    networks:
      - iep-network


volumes:
  upload_data:
  iep-mysql-data:
  qdrant-data:

networks:
  iep-network:
    external: true
