/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 課程章節 DTO
 */
export interface ChapterDto {
  /** 章節 ID */
  id?: number;
  /** 單元 ID */
  sectionId?: number;
  /** 章節名稱 */
  chapterName?: string;
  /** 章節內容 */
  content?: string;
  /** 排序索引 */
  orderIndex?: number;
}
