/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface ChapterResponse {
  id?: number;
  courseId?: number;
  date?: string;
  name?: string;
  stFile?: string;
  thFile?: string;
}
