/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 課程資訊 DTO
 */
export interface CourseDto {
  /** 課程 Id */
  id?: number;
  /** 老師 sub  */
  teacherSub?: string;
  /** 老師權限 */
  teacherRoleCode?: string;
  /** 老師名稱 */
  teacherUsername?: string;
  /** 課程名稱 */
  name?: string;
  /** 課程類型 */
  type?: string;
  /** 課程簡介 */
  intro?: string;
  /** 課程大綱 */
  outline?: string;
  /** 課程圖片 UUID */
  imageUuid?: string;
  /** 課程圖片檔名 */
  imageName?: string;
}
