/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { SectionWithChaptersDto } from './sectionWithChaptersDto';

/**
 * 課程詳細資訊 DTO（包含單元和章節）
 */
export interface CourseDetailDto {
  /** 課程 ID */
  id?: number;
  /** 老師權限 */
  teacherRoleCode?: string;
  /** 老師名稱 */
  teacherUsername?: string;
  /** 課程名稱 */
  name?: string;
  /** 課程類型 */
  type?: string;
  /** 課程簡介 */
  intro?: string;
  /** 課程大綱 */
  outline?: string;
  /** 課程圖片 UUID */
  imageUuid?: string;
  /** 課程圖片檔名 */
  imageName?: string;
  /** 課程單元列表 */
  sections?: SectionWithChaptersDto[];
}
