/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface CourseResponse {
  id?: number;
  teacherId?: number;
  teacherName?: string;
  teacherEmail?: string;
  name?: string;
  type?: string;
  intro?: string;
  outline?: string;
  imageUuid?: string;
}
