/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 課程綁定 DTO
 */
export interface EnrollmentDto {
  /** 課程綁定 ID */
  id?: number;
  /** 學生 sub */
  studentSub?: string;
  /** 課程 ID */
  courseId?: number;
}
