/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { QuestionDto } from './questionDto';

export interface QuestionsResponseDto {
  questions?: QuestionDto[];
}
