/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ChapterDto } from './chapterDto';

/**
 * 單元詳細資訊 DTO（包含章節）
 */
export interface SectionWithChaptersDto {
  /** 單元 ID */
  id?: number;
  /** 課程 ID */
  courseId?: number;
  /** 單元名稱 */
  sectionName?: string;
  /** 單元描述 */
  description?: string;
  /** 排序索引 */
  orderIndex?: number;
  /** 章節列表 */
  chapters?: ChapterDto[];
}
