/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 課程單元 DTO
 */
export interface SectionDto {
  /** 單元 ID */
  id?: number;
  /** 課程 ID */
  courseId?: number;
  /** 單元名稱 */
  sectionName?: string;
  /** 排序索引 */
  orderIndex?: number;
}
