/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 使用者資訊 DTO
 */
export interface UserInfoDto {
  /** 使用者Sub */
  sub?: string;
  /** 電子郵件 */
  email?: string;
  /** 使用者名稱 */
  username?: string;
  /** 角色代碼 */
  roleCode?: string;
}
