/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface UserChapterDto {
  chapterId?: number;
  chapterName?: string;
  courseName?: string;
  intro?: string;
  sectionName?: string;
}
