/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface UserCreateRequest {
  email?: string;
  username?: string;
  password?: string;
  roleCode?: string;
}
