/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/common/Button.vue')['default']
    ChapterManager: typeof import('./src/components/course/ChapterManager.vue')['default']
    ContentEditor: typeof import('./src/components/course/ContentEditor.vue')['default']
    CourseCard: typeof import('./src/components/course/CourseCard.vue')['default']
    CourseCardList: typeof import('./src/components/course/CourseCardList.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    FileUpload: typeof import('./src/components/common/FileUpload.vue')['default']
    Input: typeof import('./src/components/common/Input.vue')['default']
    Logo: typeof import('./src/components/NavBar/Logo.vue')['default']
    MenuLinks: typeof import('./src/components/NavBar/MenuLinks.vue')['default']
    MobileToggleBtn: typeof import('./src/components/NavBar/MobileToggleBtn.vue')['default']
    NavBar: typeof import('./src/components/NavBar/NavBar.vue')['default']
    PageTitle: typeof import('./src/components/common/PageTitle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
